version: "3"

services:
  app:
    container_name: messenger-clone-be
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - messenger-clone-be-network
    command: bash -c "npm run build && npm run start"
    depends_on:
      - mongodb
  mongodb:
    container_name: messenger-clone-db
    image: zcube/bitnami-compat-mongodb:latest
    restart: always
    ports:
      - "27018:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - messenger-clone-be-network
    volumes:
      - db-data:/bitnami/mongodb
  redis:
    image: redis:latest
    container_name: messenger-clone-be-redis
    command: redis-server --appendonly yes --replica-read-only no
    restart: always
    ports:
      - "6372:6372"
    volumes:
      - redis-data:/data
    networks:
      - messenger-clone-be-network
networks:
  messenger-clone-be-network:
volumes:
  db-data:
  redis-data:
