version: '3'
services:
  app:
    container_name: messenger-clone-be-prod
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "yarn build && yarn start"
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - messenger-clone-be-prod-network

  redis:
    image: redis:latest
    container_name: messenger-clone-be-redis-prod
    command: redis-server --appendonly yes --replica-read-only no
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - messenger-clone-be-prod-network

networks:
  messenger-clone-be-prod-network:

volumes:
  db-data:
  redis-data:
